### ISSUE TITLE
Deploy with artifactory 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-lib#1]
- library for common components between workflow 
- new repository for parent POM for all versions of node/edge/lib

**Comment by andricDu** [comment]
### Summary
This was accomplished with a simple Jenkins pipeline that tests, builds the artifact, and uses `mvn deploy` to push to artifactory. 

Here it is visible: 
![image](https://user-images.githubusercontent.com/6350043/93595906-8de8ce80-f986-11ea-87e0-165ea3dca077.png)

### Changes Made
 - Jenkinsfile added
 - Updated distribution management section of pom
 - Jenkins job created and configured
 - Readme updated

### Extra Notes
 - Could have gone the route of using the maven release plugin for automatic version management. Maybe we do that in the future but for now the current pipeline and process is inline with what we are already doing everywhere else.
